### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by crimvirt** [swalker-888/google-indexing-api-bulk#4]
HELP ME. I'M NOT GOOD AT PROGRAMMING BUT THERE'S AN ERROR IN THE CODE.

**Terminal:**

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\user\Desktop\Bulk Google Indexer\google-indexing-api-bulk-master>node index.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- C:\Users\user\Desktop\Bulk Google Indexer\google-indexing-api-bulk-master\inde
x.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\user\Desktop\Bulk Google Indexer\google-inde
xing-api-bulk-master\index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\Desktop\\Bulk Google Indexer\\google-indexing-api-bulk-mas
ter\\index.js'
  ]
}

C:\Users\user\Desktop\Bulk Google Indexer\google-indexing-api-bulk-master>

**Comment by salvatorecapolupo** [comment]
Please check this for the solution: https://stackoverflow.com/questions/16482600/node-js-cannot-find-module-request

**Comment by swalker-888** [comment]
request has been added as a dependency so should be included when installing the modules with 'npm install'
